title: Soham Bhagwat
logo: /assets/img/logo.jpg
# email: bogus at gmail dot com
description: ""
show_downloads: false
blank_title: true
google_analytics: UA-000000-0
color-scheme: light
favicon: true
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/the-soham
  - name: CV
    icon: <i class="fas fa-file-pdf"></i>
    link: /Soham_Bhagwat_Resume.pdf
  - name: LinkedIn
    icon: <i class="fab fa-linkedin"></i>
    link: https://www.linkedin.com/in/soham-bhagwat/

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
