title: Soham Bhagwat # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
   Master's student pursuing Data Science <br> @  <a href="https://www.iu.edu/">Indiana University</a>-Bloomington
  <br>
  I completed my undergrad at SPPU with BE in Computer Engg. with honors in AI and ML. 
  <br><br>
  <a href="https://www.linkedin.com/in/soham-bhagwat/">LinkedIn</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="https://github.com/the-soham">Github</a> &nbsp;&nbsp;&nbsp;&nbsp;<a href="/pdf/Soham_Bhagwat.pdf">CV</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
